### ISSUE TITLE
Updates Internal IP not External Public IP

### ISSUE THREAD

**Issue by Wasca** [EsotericSoftware/dnsmadeeasy#7]
Hi 

I'm running version 1.7 on the latest version of Windows 10. When the IP updates it's getting the local LAN IP instead of the PC's Public IP address. Any idea why it's doing this?

**Comment by NathanSweet** [comment]
Sorry for the delay.

I don't know why it would do that. It hits http://myip.dnsmadeeasy.com/ here:
https://github.com/EsotericSoftware/dnsmadeeasy/blob/master/src/com/esotericsoftware/dnsmadeeasy/DnsMadeEasy.java#L49
What does that URL give you?

**Comment by Wasca** [comment]
@NathanSweet I just tested that URL and it is giving me the correct public IP address when I hit it. Sorry for the fuss, not sure what was going on.
